server:
  port: 8090
spring:
  application:
    name: GymMicroserviceApplication
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gym-group
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    template:
      default-topic: gym-topic
token:
  expiration: 30000000
  key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A753HY123ID1123"

cors:
  allowed-origins: "http://localhost**"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true


