server:
  port: 8090
spring:
  application:
    name: GymMicroserviceApplication
  data:
    mongodb:
      host: localhost
      port: 27017
      username: gym
      password: gym
      auto-index-creation: true
      uri: mongodb://gym:gym@localhost:27017
      authentication-database: gym
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gym-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: localhost:9092
    template:
      default-topic: gym-topic

token:
  expiration: 30000000
  key: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A753HY123ID1123"

cors:
  allowed-origins: "http://localhost**"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true
logging:
  level:
    root: INFO
    com.gym.gymmicroservice: DEBUG


